CREATE TABLE TB_USUARIOS(
	ID_USUARIO INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	NOMBRE VARCHAR(50) NOT NULL,
	CONTRASENA VARCHAR(600) NOT NULL
);
--------------------------------------------------------------------------------
CREATE TABLE TB_DATOSCLIENTE(
	ID_CLIENTE INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	CEDULA VARCHAR(50) NOT NULL,
	NOMBRE VARCHAR(50) NOT NULL,
	NOMBRE_COMPLETO VARCHAR(100) NOT NULL,
	APELLIDO VARCHAR(50) NOT NULL,
	TELEFONO VARCHAR(50) NOT NULL,
	CORREO VARCHAR(100) NOT NULL,
	DIRECCION VARCHAR(100) NOT NULL,
	ID_GENERO INT NOT NULL,
	ID_SECTOR INT NOT NULL,
	FECHA_INGRESO DATE NOT NULL,
	ACTIVO BIT NOT NULL,

	FOREIGN KEY (ID_GENERO) REFERENCES TB_GENERO(ID_GENERO),
	FOREIGN KEY (ID_SECTOR) REFERENCES TB_SECTOR(ID_SECTOR)
);

UPDATE TB_DATOSCLIENTE SET ACTIVO = 1

CREATE TABLE TB_GENERO(
	ID_GENERO INT IDENTITY(1,1) PRIMARY KEY,
	NOMBRE VARCHAR(50) NOT NULL,
	ACTIVO BIT NOT NULL
);
INSERT INTO TB_GENERO values('Masculino',1);
INSERT INTO TB_GENERO VALUES('Femenino',1);

CREATE TABLE TB_SECTOR(
	ID_SECTOR INT IDENTITY(1,1) PRIMARY KEY,
	NOMBRE VARCHAR(50) NOT NULL,
	ACTIVO BIT NOT NULL
);
INSERT INTO TB_SECTOR values('Sur',1);
INSERT INTO TB_SECTOR VALUES('Norte',1);
INSERT INTO TB_SECTOR VALUES('Centro',1);
--------------------------------------------------------------------------------

CREATE TABLE TB_DATOSTECNICO(
	ID_TECNICO INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	CEDULA VARCHAR(50) NOT NULL,
	NOMBRE VARCHAR(50) NOT NULL,
	NOMBRE_COMPLETO VARCHAR(100) NOT NULL,
	APELLIDO VARCHAR(50) NOT NULL,
	TELEFONO VARCHAR(50) NOT NULL,
	CORREO VARCHAR(100) NOT NULL,
	ID_ESPECIALIDAD INT NOT NULL,
	FECHA_INGRESO DATE NOT NULL,
	ACTIVO BIT NOT NULL
	FOREIGN KEY (ID_ESPECIALIDAD) REFERENCES TB_ESPECIALIDAD(ID_ESPECIALIDAD)
);
--------------------------------------------------------------------------------

CREATE TABLE TB_ESPECIALIDAD(
	ID_ESPECIALIDAD INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	NOMBRE VARCHAR(50) NOT NULL,
	ACTIVO BIT
);


INSERT INTO TB_ESPECIALIDAD VALUES('Especialidad en Telefono Android',1);
INSERT INTO TB_ESPECIALIDAD VALUES('Especialidad en Telefono Huawei',1);
INSERT INTO TB_ESPECIALIDAD VALUES('Especialidad en Telefono Iphone',1);
INSERT INTO TB_ESPECIALIDAD VALUES('Especialidad en Telefono Xiaomi',1);
INSERT INTO TB_ESPECIALIDAD VALUES('Especialidad con Todos los Telefono',1);

--------------------------------------------------------------------------------
CREATE TABLE TB_DISPOSITIVO(
	ID_DISPOSITIVO INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	ID_CLIENTE INT NOT NULL,
	ID_TIPO INT NOT NULL,
	ID_SISTEMA INT NOT NULL,
	MARCA VARCHAR(50) NOT NULL,
	MODELO VARCHAR(50) NOT NULL,
	ANIO VARCHAR(50) NOT NULL,
	FECHA_INGRESO DATE NOT NULL,
	ACTIVO BIT NOT NULL

	FOREIGN KEY (ID_CLIENTE) REFERENCES TB_DATOSCLIENTE(ID_CLIENTE),
	FOREIGN KEY (ID_TIPO) REFERENCES TB_TIPODISPOSITIVO(ID_TIPO),
	FOREIGN KEY (ID_SISTEMA) REFERENCES TB_TIPOSISTEMA(ID_SISTEMA)
);

CREATE TABLE TB_TIPODISPOSITIVO(
	ID_TIPO INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	NOMBRE VARCHAR(50) NOT NULL,
	ACTIVO BIT NOT NULL
);
INSERT INTO TB_TIPODISPOSITIVO VALUES('Table',1);
INSERT INTO TB_TIPODISPOSITIVO VALUES('Smartphone',1);
INSERT INTO TB_TIPODISPOSITIVO VALUES('iPad',1);


CREATE TABLE TB_TIPOSISTEMA(
	ID_SISTEMA INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	NOMBRE VARCHAR(50) NOT NULL,
	ACTIVO BIT NOT NULL
);
INSERT INTO TB_TIPOSISTEMA VALUES('Android',1);
INSERT INTO TB_TIPOSISTEMA VALUES('IOS',1);

-------------------------------------------------------------------------------
CREATE TABLE TB_REPARACION(
	ID_REPARACION INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	ID_DISPOSITIVO INT NOT NULL,
	ID_TECNICO INT NOT NULL,
	REPUESTOS VARCHAR(250) NOT NULL,
	TOTAL_REPUESTOS VARCHAR(50) NOT NULL,
	SERVICIO VARCHAR(250) NOT NULL,
	TOTAL_SERVICIO VARCHAR(50) NOT NULL,
	FECHA_REPARACION VARCHAR(50) NOT NULL,
	ACTIVO BIT NOT NULL,

	FOREIGN KEY (ID_DISPOSITIVO) REFERENCES TB_DISPOSITIVO(ID_DISPOSITIVO),
	FOREIGN KEY (ID_TECNICO) REFERENCES TB_DATOSTECNICO(ID_TECNICO),
);
